"""Phase-3 summary report over all real-pipeline runs (and E3 bandwidth benchmarks).

    python -m timeprest.report                       # scans results/phase2, results/phase3, results/tinyimagenet
    python -m timeprest.report --roots results/phase3 --out results/phase3/report.md

A run is any directory with metrics.csv + config.json; a benchmark is a directory with
bench_comm.json. Writes a markdown file of tables (numbers only; the analysis lives in
paper_notes.md).
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import statistics

from .utils import read_csv

TARGETS = {"cifar100": (60.0, 65.0, 70.0, 72.0), "tinyimagenet": (40.0, 45.0, 50.0, 55.0)}
DEFAULT_TARGETS = (60.0, 65.0, 70.0, 72.0)
# Paper values read from figures (paper_notes §20.1, Fig.4b, VGG-16/CIFAR-100, Cluster A, W=2).
PAPER = {"CIFAR-100, Fig.4b top-1 at ~160 epochs (Cluster A, W=2)": "TiMePReSt ~72-75 %, PipeDream ~73-77 %",
         "Tiny-ImageNet-200, Fig.8b top-1 at ~140 epochs (Cluster B, W=3)": "TiMePReSt ~68-72 %, PipeDream ~73-77 %"}


def _floats(rows, key):
    return [float(r[key]) for r in rows]


def _split(v: str) -> list[float]:
    return [float(x) for x in str(v).split("|")]


def _group(path: str) -> str:
    """runN_... directory a run belongs to (skipping a plain `runs/` level)."""
    parent = os.path.dirname(os.path.normpath(path))
    if os.path.basename(parent) == "runs":
        parent = os.path.dirname(parent)
    return os.path.basename(parent)


def summarize_run(path: str) -> dict:
    rows = read_csv(os.path.join(path, "metrics.csv"))
    cfg = json.load(open(os.path.join(path, "config.json"), encoding="utf-8"))
    pc, tc = cfg["pipeline"], cfg["training"]
    acc, cum, t = _floats(rows, "test_acc1"), _floats(rows, "cum_time_s"), _floats(rows, "epoch_time_s")
    dataset = cfg.get("data", {}).get("dataset", "?")
    reach = {}
    for th in TARGETS.get(dataset, DEFAULT_TARGETS):
        i = next((k for k, a in enumerate(acc) if a >= th), None)
        reach[th] = (i + 1, cum[i] / 3600) if i is not None else (None, None)
    last = rows[-1]
    return {
        "group": _group(path), "run": os.path.basename(path.rstrip("/\\")),
        "system": cfg["system"], "schedule": pc["schedule"], "dataset": dataset,
        # stashed: forward and backward versions coincide, both rules give the same gradients;
        # runs before §22.6 have no backward_rule key and used recompute
        "rule": "F=B version" if pc["backward_version"] == "stashed" else (pc.get("backward_rule") or "recompute"),
        "N": pc["num_microbatches"], "M": tc["batch_size"], "lr": tc["lr"], "epochs": len(rows),
        "final": acc[-1], "last10": sum(acc[-10:]) / min(10, len(acc)), "best": max(acc),
        "reach": reach, "epoch_s": statistics.median(t), "total_h": cum[-1] / 3600,
        "mem": _split(last["peak_mem_mb"]), "busy": _split(last["busy_frac"]),
        "recompute": last.get("recompute_micro"), "overlap": last.get("bwd_overlap_minibatches"),
    }


def _fmt_reach(r):
    return " / ".join("-" if e is None else str(e) for e, _ in r.values())


def _fmt_hours(r):
    return " / ".join("-" if h is None else f"{h:.2f}" for _, h in r.values())


def render(runs: list[dict], benches: list[tuple[str, dict]]) -> str:
    out = ["# Phase-3 report (generated by `python -m timeprest.report`)", ""]
    for dataset in dict.fromkeys(r["dataset"] for r in runs):
        ths = "/".join(f"{int(t)}" for t in TARGETS.get(dataset, DEFAULT_TARGETS))
        out += [f"## Runs: {dataset} (real 2-GPU pipeline, VGG-16-BN)", "",
                f"| group | run | system | backward | sched | N | M | lr | epochs | top-1 final | last-10 mean | best | "
                f"epochs to {ths} % | hours to {ths} % | epoch (s, median) | total (h) | peak MB per GPU | busy per GPU |",
                "|" + "---|" * 18]
        out += [_run_line(r) for r in runs if r["dataset"] == dataset]
        out.append("")
    return _render_rest(out, benches)


def _run_line(r) -> str:
    return (f"| {r['group']} | {r['run']} | {r['system']} | {r['rule']} | {r['schedule']} | "
            f"{r['N']} | {r['M']} | {r['lr']} | {r['epochs']} | {r['final']:.2f} | {r['last10']:.2f} | {r['best']:.2f} | "
            f"{_fmt_reach(r['reach'])} | {_fmt_hours(r['reach'])} | {r['epoch_s']:.2f} | {r['total_h']:.2f} | "
            f"{' / '.join(f'{m:.0f}' for m in r['mem'])} | {' / '.join(f'{b:.2f}' for b in r['busy'])} |")


def _render_rest(out: list[str], benches) -> str:
    out += ["## Paper reference", ""] + [f"- {k}: {v}" for k, v in PAPER.items()]
    for path, b in benches:
        rows = b["rows"]
        systems = list(dict.fromkeys(r["system"] for r in rows))
        out += ["", f"## Epoch time vs emulated bandwidth (`{path}`, latency {b['bench'].get('latency_ms')} ms/message)", "",
                "| bandwidth (Gbit/s) | " + " | ".join(f"{s} epoch (s)" for s in systems)
                + (f" | {systems[0]} / {systems[1]} |" if len(systems) > 1 else " |"),
                "|" + "---|" * (len(systems) + 1 + (len(systems) > 1))]
        for bw in b["bench"]["bandwidths_gbps"]:
            t = {r["system"]: r["epoch_time_s"] for r in rows if r["bandwidth_gbps"] == bw}
            line = f"| {bw or 'none (same host)'} | " + " | ".join(f"{t[s]:.2f}" if s in t else "-" for s in systems)
            if len(systems) > 1:
                line += f" | {t[systems[0]] / t[systems[1]]:.3f}" if systems[0] in t and systems[1] in t else " | -"
            out.append(line + " |")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--roots", nargs="+", default=["results/phase2", "results/phase3", "results/tinyimagenet"])
    ap.add_argument("--out", default="results/phase3/report.md")
    args = ap.parse_args(argv)
    runs, benches = [], []
    for root in args.roots:
        for d in sorted(glob.glob(os.path.join(root, "**", "metrics.csv"), recursive=True)):
            d = os.path.dirname(d)
            if os.path.exists(os.path.join(d, "config.json")) and "bench_" not in os.path.basename(d):
                runs.append(summarize_run(d))
        for f in sorted(glob.glob(os.path.join(root, "**", "bench_comm.json"), recursive=True)):
            benches.append((os.path.dirname(f), json.load(open(f, encoding="utf-8"))))
    text = render(runs, benches)
    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)
    print("saved", args.out)


if __name__ == "__main__":
    main()
